import type { HerbDetail } from "./herb-descriptions";

export const herbDetailsExtra: Record<string, HerbDetail> = {
  gokshura: {
    appearance: "A low-growing, spreading annual herb with paired compound leaves and small yellow flowers. Its most distinctive feature is the spiny, star-shaped fruit — sharp enough to puncture bicycle tires, earning it the name 'puncture vine.' The entire plant is covered in fine silky hair and grows in sandy, arid soils.",
    history: "Called 'Gokhru' (cow's hoof) because its spiny fruit resembles a cow's footprint. It has been used in Ayurveda for over 2,000 years primarily for urinary and reproductive health. In ancient India, warriors consumed it for strength and stamina. It is also prominent in Traditional Chinese Medicine as 'Ji Li' and in Unani medicine as 'Khar-e-Khasak.'",
    medicinal: "Contains protodioscin and furostanol saponins. Clinical trials show it improves urinary tract function, supports kidney health, and enhances physical performance. Research confirms it increases luteinizing hormone, supporting natural testosterone production. It also protects kidney tissue from oxidite damage and reduces the size of kidney and bladder stones."
  },
  gudmar: {
    appearance: "A woody, climbing vine with oval, velvety leaves that can reach 3–4 meters in length. Small yellow bell-shaped flowers grow in umbels. The leaves have a remarkable property: when chewed, they temporarily suppress the ability to taste sweetness — sugar tastes like sand on the tongue for up to two hours.",
    history: "The name 'Gudmar' literally translates to 'sugar destroyer' — describing its extraordinary taste-blocking property. It has been used in Ayurveda for over 2,000 years specifically for Madhumeha (diabetes). Ancient practitioners would ask patients to chew the leaf before meals to reduce sugar cravings. It is one of the most researched anti-diabetic herbs globally.",
    medicinal: "Contains gymnemic acids that are structurally similar to glucose molecules. They block sugar receptors on taste buds AND intestinal sugar absorption. Clinical studies demonstrate significant HbA1c reduction. The compounds also stimulate pancreatic beta-cell regeneration. Multiple pharmaceutical companies are studying gymnemic acids as a basis for diabetes drugs."
  },
  haridra: {
    appearance: "Identical in appearance to common turmeric — a tropical perennial with broad lance-shaped leaves emerging from underground rhizomes. The rhizomes are bright orange-yellow inside with a characteristic warm, peppery aroma. In Ayurveda, Haridra specifically refers to turmeric used medicinally rather than as a spice.",
    history: "While turmeric is the culinary name, 'Haridra' is the Ayurvedic medicinal name emphasizing its therapeutic applications. It has been used specifically as a blood purifier and wound healer in Ayurvedic hospitals for millennia. The Sushruta Samhita prescribes Haridra paste for virtually every skin condition. It remains the most commonly prescribed herb in Ayurvedic dermatology.",
    medicinal: "When used medicinally, standardized extracts provide higher concentrations of curcuminoids than dietary turmeric. It specifically targets blood purification (Raktashodhaka), liver detoxification, and skin disorders. Applied topically with neem and sandalwood, it treats acne, eczema, and psoriasis. Internally, it supports liver metabolism and reduces systemic allergic responses."
  },
  haritaki: {
    appearance: "A large deciduous tree (25–30 m) with a cylindrical trunk, spreading crown, and simple, ovate leaves. Its fruit — small, ovoid, with five prominent ridges — dries into a hard, dark brown drupe resembling a dried prune. The taste is initially astringent but leaves a sweet aftertaste.",
    history: "Called 'The King of Medicines' in Tibetan Buddhism and depicted in the hand of the Medicine Buddha. It is considered the single most important herb in Tibetan medicine. In Ayurveda, Charaka calls it the best Rasayana. Seven types of Haritaki are classified based on shape and region, each with different therapeutic strengths. It is the third fruit of Triphala.",
    medicinal: "Contains chebulic acid, chebulagic acid, and gallic acid. Research confirms powerful antioxidant, anti-mutagenic, and cardioprotective effects. It gently regulates bowel movements while nourishing the gut wall — unlike harsh laxatives. Studies demonstrate cognitive enhancement, anti-diabetic effects, and significant wound-healing acceleration."
  },
  kamdhudha: {
    appearance: "Not a plant but a classical Ayurvedic mineral-herbal formulation — a fine, white-to-pale-grey powder with a mildly chalky texture. It is prepared by triturating purified pearl (Mukta), coral (Praval), and conch shell (Shankh) with herbal juices, then processing them through specific heating protocols described in ancient Rasa Shastra texts.",
    history: "A revered formulation from the Rasa Shastra tradition of Ayurvedic mineral medicine. 'Kamdudha' means 'the wish-fulfilling divine cow,' named after Kamadhenu — the celestial cow that grants all desires. It has been prepared by Ayurvedic pharmacies for centuries specifically for Pitta-related burning sensations, hyperacidity, and gastritis.",
    medicinal: "Acts as a natural antacid and cooling agent. The calcium and mineral compounds neutralize excess stomach acid, soothe inflamed gastric mucosa, and reduce Pitta aggravation. Clinically used for acid reflux, peptic ulcers, burning urination, and menopausal hot flashes. It is considered safer than synthetic antacids for long-term use under practitioner guidance."
  },
  kanchanar: {
    appearance: "A medium-sized deciduous tree (8–12 m) producing one of India's most beautiful flowers — orchid-like, with five petals that range from white to magenta with vivid purple streaks. Its leaves are distinctive — bilobed, resembling a camel's footprint. The bark is grey-brown and the seedpods are flat and woody.",
    history: "Called the 'orchid tree' for its stunning blooms, Kanchanar has been used medicinally for over 2,000 years. The Bhavaprakasha Nighantu specifically prescribes its bark for Gandamala (lymphatic swellings and thyroid goiter). It is the primary herb in the famous Kanchanar Guggulu formulation — Ayurveda's most important preparation for thyroid and lymphatic disorders.",
    medicinal: "Contains lupeol, beta-sitosterol, and kaempferol. Research shows significant anti-thyroid and thyroid-modulating activity — making it useful for both hypo and hyperthyroidism. Its anti-lymphoproliferative action helps manage lymphadenopathy, lipomas, and benign tumors. Studies also confirm antioxidant, anti-inflammatory, and wound-healing properties."
  },
  karela: {
    appearance: "A tropical climbing vine with deeply lobed, palmate leaves and distinctive warty, oblong fruits that look like bumpy cucumbers. The fruit is bright green when unripe, turning yellow-orange when mature. Inside, the flesh is watery and extremely bitter — the most bitter of any edible fruit — with flat, red-coated seeds.",
    history: "Known as 'Bitter Melon' or 'Bitter Gourd,' it has been cultivated across Asia, Africa, and South America for thousands of years. In Ayurveda, it is classified as a premier Prameha herb (anti-diabetic). Indian grandmothers have long insisted on including karela in the family diet at least weekly. Despite its bitterness, it is a beloved vegetable in Indian, Chinese, and Filipino cuisine.",
    medicinal: "Contains charantin, vicine, and polypeptide-p (plant insulin). Multiple clinical trials confirm blood glucose reduction of 15–25% in type-2 diabetics. It also activates AMP-activated protein kinase (AMPK), improving glucose uptake. Rich in Vitamin C and antioxidants, it supports liver detox, reduces blood lipids, and has shown anti-cancer activity in laboratory studies."
  },
  kashmari: {
    appearance: "A large deciduous tree (15–20 m) with a straight trunk, spreading crown, and large, heart-shaped leaves. Its flowers are tubular, yellow-brown with a pleasant fragrance. The fruit is a fleshy drupe — green ripening to yellow — with edible sweet pulp surrounding a hard stone. The bark is grey and rough.",
    history: "An important component of the Dashamoola (ten roots) formula — one of Ayurveda's most fundamental preparations. Charaka classifies it as Shothahara (anti-inflammatory) and Balya (strength-giving). Ancient texts recommend its fruit pulp for building strength during convalescence and its root bark for reducing inflammation and pain.",
    medicinal: "Contains arborone, gmelinol, and luteolin. Research shows anti-inflammatory activity comparable to indomethacin. The fruit is nutritive and used to manage debility and urinary disorders. Root decoction improves digestive fire and treats fever. It also exhibits analgesic, diuretic, and aphrodisiac properties confirmed by pharmacological studies."
  },
  katuka: {
    appearance: "A small, perennial herb growing 5–15 cm in high Himalayan meadows (3,000–4,500 m). It has toothed, spatula-shaped basal leaves forming a rosette close to the ground. Pale blue or purple flowers bloom on short spikes. The rhizome — dark, creeping, and extremely bitter — is the medicinal part.",
    history: "Called 'Kutki' in Hindi and 'Katuka Rohini' in Sanskrit, meaning 'intensely bitter.' It has been the primary liver-protective herb in Ayurveda for over 2,500 years. Ancient physicians prescribed it for Kamala (jaundice), Yakrit Vikara (liver disorders), and intermittent fevers. Due to overharvesting, it is now an endangered species in the wild.",
    medicinal: "Contains kutkin (picroside I and II) — compounds with scientifically validated hepatoprotective activity comparable to silymarin. It stimulates bile secretion, protects hepatocytes from toxin damage, and aids liver regeneration. Also has potent immunomodulatory, anti-asthmatic, and anti-allergic properties. It is used clinically for hepatitis, jaundice, and immune disorders."
  },
  kumari: {
    appearance: "A succulent perennial with thick, fleshy, lance-shaped leaves arranged in a rosette pattern. Each leaf is green to grey-green with serrated edges and sharp terminal spine. When cut, the leaf reveals two products: a clear, viscous inner gel and a yellow latex layer just beneath the rind. Plants can grow 60–100 cm tall.",
    history: "Known globally as Aloe Vera, called 'Kumari' (young maiden) in Ayurveda — named for its remarkable ability to bestow youthful skin. Cleopatra used it as part of her beauty regimen. Ancient Mesopotamian clay tablets from 2,100 BCE describe its healing properties. In Ayurveda, it has been used for skin burns, digestive issues, and female reproductive health for millennia.",
    medicinal: "The gel contains acemannan, aloin, vitamins, minerals, amino acids, and enzymes. Clinically proven to accelerate wound healing by 35%, soothe burns, and hydrate skin. Internally, the juice supports digestive health and acts as a mild laxative. Research confirms anti-diabetic, immunostimulant, and anti-tumor properties. It also reduces dental plaque as effectively as chlorhexidine."
  },
  kutki: {
    appearance: "Identical to Katuka — a small alpine herb with basal leaf rosettes, as both names refer to Picrorhiza kurroa. The rhizome is dark brown, woody, and extremely bitter, breaking with a clean fracture. It is harvested from rocky Himalayan slopes and dried in high-altitude sunlight.",
    history: "Kutki and Katuka are regional names for the same plant. Its trade has been documented along Himalayan routes for over a thousand years. In the Tibetan medical system, it is called 'Hong-Len' and is equally prized. Modern conservation efforts are underway as demand far exceeds wild supply, with tissue-culture propagation programs across India and Nepal.",
    medicinal: "The same kutkin compounds provide powerful hepatoprotection, making it a first-line Ayurvedic treatment for viral hepatitis. Clinical trials show it reduces elevated liver enzymes within weeks. Its iridoid glycosides also modulate the immune system — useful in autoimmune conditions. It is being researched as a natural alternative to corticosteroids for certain inflammatory conditions."
  },
  lodhra: {
    appearance: "A medium-sized evergreen tree (5–10 m) with thick, grey-brown bark and oblong, leathery, dark-green leaves. Small white fragrant flowers bloom in dense axillary clusters. The bark — the main medicinal part — is grey, fibrous, and astringent, releasing a reddish tincture when soaked in water.",
    history: "One of Ayurveda's most important herbs for women's health, mentioned extensively by Charaka and Sushruta for Stri Roga (gynecological disorders). Its bark was traditionally powdered and used as a face pack for clear, radiant skin — a beauty secret of ancient Indian women. It is also used as a natural dye for fabrics.",
    medicinal: "Contains loturine, loturidine, and flavonoids. Research confirms it regulates female reproductive hormones — particularly beneficial for PCOS and irregular menstruation. It reduces excess uterine bleeding and supports ovulation. Applied topically, it treats acne and pigmentation. Studies also show anti-inflammatory, anti-tumor, and hepatoprotective activity."
  },
  musta: {
    appearance: "A slender sedge grass growing 20–75 cm with triangular stems, narrow grass-like leaves, and small reddish-brown flower spikelets in umbel-like clusters. Underground, it produces dark, aromatic tubers — small, ovoid, and covered in dark brown skin with white starchy flesh and a distinctive camphor-like fragrance.",
    history: "One of the most ancient medicinal plants, used in Ayurveda, Egyptian, and Greek medicine for over 4,000 years. Charaka lists it as the best herb for Ama Pachana (digesting metabolic toxins). Ancient Egyptian papyri mention its use for fever and women's complaints. In India, it is commonly called 'Nagarmotha' and used in traditional perfumery as well.",
    medicinal: "Contains cyperene, cyperol, and alpha-cyperone — terpenoids with proven anti-inflammatory and analgesic properties. Particularly effective for digestive complaints: bloating, diarrhea, IBS, and loss of appetite. Research shows significant anti-malarial activity. It also regulates menstrual cycles, reduces dysmenorrhea, and exhibits anti-diabetic and anti-obesity effects."
  },
  nagarmotha: {
    appearance: "Very similar to Musta — a sedge plant with triangular stems and aromatic underground tubers. The two are closely related species within the Cyperus genus. Nagarmotha tubers tend to be slightly more elongated and have a more pronounced warm, woody, earthy fragrance used extensively in Indian Attar perfumery.",
    history: "While Musta refers to the medicinal context, 'Nagarmotha' is the common Hindi name used widely in North Indian folk medicine and the perfume industry. The fragrant tuber has been distilled into essential oil for centuries in Kannauj — India's perfume capital. It was an important trade commodity along ancient spice routes.",
    medicinal: "Shares many properties with Musta due to similar chemistry. Its essential oil is a powerful antifungal — effective against Candida and dermatophytes. The tuber decoction treats childhood fevers, digestive complaints, and skin infections. It is also used as a natural fumigant and insect repellent in traditional Indian households."
  },
  nagkesar: {
    appearance: "A large, stately evergreen tree (18–30 m) called the 'Indian Rose Chestnut' or 'Ironwood.' Its wood is extremely hard and dense. The tree produces magnificent, large, fragrant white flowers with a central golden cluster of hundreds of stamens — resembling a burst of sunshine. Its bark is thick and deeply fissured.",
    history: "The name means 'serpent's flower' in Sanskrit. Its flowers have been used in Indian temple offerings and traditional medicine for over 2,000 years. Sushruta specifically prescribes it for Raktapitta (bleeding disorders). The timber is so dense it sinks in water and has been used for centuries in shipbuilding and railway sleepers across South and Southeast Asia.",
    medicinal: "The stamens contain mesuaferrone, mesuol, and xanthones — compounds with proven hemostatic (blood-clotting), anti-inflammatory, and analgesic properties. Clinically used for bleeding piles, menorrhagia, and bleeding ulcers. It also shows anti-bacterial activity against H. pylori, anti-venom properties, and has been researched for anti-cancer potential."
  },
  pippali: {
    appearance: "A slender, aromatic climbing pepper vine with heart-shaped leaves and catkin-like flower spikes that mature into small, cylindrical fruit clusters — resembling tiny elongated pinecones. When dried, these spikes turn greyish-black and have a pungent, warming taste distinctly different from regular black pepper.",
    history: "Long Pepper was actually more prized than black pepper in ancient times — Roman records show it traded at three times the price of black pepper. It is one of the three ingredients in the famous Trikatu ('three pungents') formula. Charaka recommends it as the premier Rasayana taken with honey and ghee in gradually increasing and decreasing doses — the Vardhamana Pippali protocol.",
    medicinal: "Contains piperine and piperlongumine — bioavailability enhancers that can increase absorption of other nutrients by 30–200%. This makes it a critical bioenhancer in Ayurvedic formulations. Research shows bronchodilatory effects for asthma, hepatoprotective activity, immunomodulatory benefits, and emerging anti-cancer properties through selective tumor cell apoptosis."
  },
  sariva: {
    appearance: "A twining, semi-evergreen vine with opposite, smooth, ovate leaves and small greenish-purple flowers in dense cymes. The roots — long, slender, tortuous, and woody with a dark reddish-brown exterior — have a distinctive sweet, vanilla-like fragrance. The entire plant exudes a milky latex when cut.",
    history: "Called 'Indian Sarsaparilla' (though botanically unrelated to American sarsaparilla), it has been used in Ayurveda for over 2,500 years as the supreme blood cooler. Its fragrant root is used to make a beloved traditional Indian summer drink — Nannari sherbet — served across South India to beat the heat. It is also the base for many Ayurvedic skin-care formulations.",
    medicinal: "Contains hemidesmin, hemidescine, and coumarins. A powerful blood purifier and coolant, it specifically addresses Pitta-related skin disorders — acne, rashes, and burning sensations. Clinical research shows anti-inflammatory, antioxidant, and nephroprotective properties. It is also effective for urinary tract infections and is used to treat syphilis in traditional practice."
  },
  sarpagandha: {
    appearance: "A small, erect evergreen shrub (60–90 cm) with whorled, glossy dark-green leaves and clusters of small white or pink tubular flowers. It produces small, glossy, purple-black drupes. The root — the primary medicinal part — is brownish, twisted, and deeply bitter. The plant grows in the undergrowth of moist tropical forests.",
    history: "One of the most historically significant medicinal plants in modern pharmacology. Mahatma Gandhi reportedly used it as a tranquilizer. In 1952, its alkaloid reserpine was isolated and became the FIRST effective drug for treating hypertension in Western medicine — revolutionizing cardiology. This discovery validated Ayurvedic knowledge that had prescribed this root for 'insanity and hypertension' for thousands of years.",
    medicinal: "Contains reserpine, ajmaline, and serpentine — powerful indole alkaloids. Reserpine depletes catecholamine stores, reducing blood pressure and inducing sedation. Ajmaline is used as an anti-arrhythmic drug worldwide. Due to its potency, it must ONLY be used under medical supervision. Side effects at high doses include severe depression and nasal congestion."
  },
  dashamula: {
    appearance: "Not a single plant but a classical group of ten roots — five from large trees (Bilva, Agnimantha, Shyonaka, Patala, Gambhari) and five from smaller plants (Brihati, Kantakari, Gokshura, Shalaparni, Prishniparni). The dried roots are combined and decocted together to create a dark, aromatic, bitter-sweet brew.",
    history: "One of the most ancient and important formulations in Ayurveda, mentioned in every major classical text. The name means 'ten roots.' It is the foundational preparation used in Panchakarma therapy — especially for Basti (medicated enema). It specifically targets Vata dosha and is prescribed for post-partum recovery, pain, inflammation, and respiratory distress.",
    medicinal: "The synergy of ten roots provides broad-spectrum anti-inflammatory, analgesic, and anti-spasmodic effects. Research shows it reduces inflammatory markers (TNF-alpha, IL-6) significantly. It is clinically used for rheumatic pain, sciatica, respiratory disorders, and post-surgical recovery. The decoction also has febrifuge and diuretic properties."
  },
  devdaru: {
    appearance: "The majestic Himalayan Cedar (Deodar) — a towering coniferous evergreen reaching 40–60 meters with a pyramidal crown, horizontal spreading branches, and clusters of needle-like leaves. Its wood is highly aromatic, golden-brown, and naturally decay-resistant. Massive cones sit upright on branches, disintegrating at maturity.",
    history: "The name means 'wood of the gods' in Sanskrit. These ancient trees can live over 1,000 years and are sacred in Hinduism. The great temples of Kashmir were built with Deodar wood. It is the national tree of Pakistan and the state tree of Himachal Pradesh. Its essential oil (Devdaru Taila) has been used in Ayurvedic medicine for millennia for joint and respiratory ailments.",
    medicinal: "Contains himachalol, atlantone, and deodarone — sesquiterpenes with proven anti-inflammatory, analgesic, and insecticidal properties. The oil is used externally for arthritis, joint pain, and muscle stiffness. Internally, the bark decoction treats urinary disorders and fever. Research shows diuretic, anti-diabetic, and anti-anxiety activity."
  },
  vacha: {
    appearance: "A semi-aquatic perennial growing 30–100 cm in marshes and streamsides, with long, sword-shaped aromatic leaves emerging from a creeping rhizome. The rhizome is the medicinal part — cylindrical, spongy, pinkish-brown externally and white internally, with a strong, camphor-like, pungent aroma.",
    history: "Known as Sweet Flag or Calamus, it has been used across Ayurveda, Traditional Chinese Medicine, and European herbal medicine for over 3,000 years. In Ayurveda, it is the premier herb for speech disorders and learning disabilities in children. Ancient scholars placed it under their tongues before debates. It is also used ritually for purification and to ward off negative energies.",
    medicinal: "Contains alpha- and beta-asarone — compounds with proven neurostimulant, anti-convulsant, and memory-enhancing properties. It improves speech clarity and articulation — used therapeutically for stuttering and speech delays. Research shows it enhances GABA and serotonin levels. Also effective as a digestive and bronchodilator. Note: high doses of beta-asarone are restricted in some countries."
  },
  vidanga: {
    appearance: "A large, climbing shrub with long, flexible branches, leathery oblong leaves, and small white flowers in long racemes. Its fruit — the primary medicinal part — is a tiny, round, reddish-brown berry resembling black pepper but slightly smaller, with a pungent, astringent taste. The dried berries are the standard medicinal form.",
    history: "The premier anti-parasitic herb in Ayurveda for over 3,000 years. Charaka lists it as the best Krimighna (worm destroyer). In ancient India, it was routinely given to children during monsoon season when parasitic infections peaked. Beyond anti-parasitic use, it is also mentioned as a Rasayana and Medhya herb — believed to sharpen intelligence when taken regularly.",
    medicinal: "Contains embelin — a quinone compound with potent anti-helminthic, antibacterial, and antioxidant activity. Research confirms its effectiveness against roundworms, tapeworms, and other intestinal parasites. It also shows significant anti-fertility activity (being researched as a natural contraceptive), anti-tumor properties, and anti-inflammatory effects."
  },
  vidari: {
    appearance: "A massive perennial climbing vine with large, three-lobed leaves and beautiful purple-blue butterfly-shaped flowers in dense racemes. Underground, it produces enormous tuberous roots — sometimes weighing over 10 kg — with brown skin and white, starchy, milky flesh. The tuber is the primary medicinal part.",
    history: "Called 'Indian Kudzu,' it is one of Ayurveda's most important nourishing (Brimhana) herbs — prescribed for emaciation, weakness, and low vitality. Charaka classifies it as Balya (strength-giving) and Jivaniya (life-sustaining). It was traditionally given to new mothers as a galactagogue and to the elderly for rejuvenation. Athletes consumed it for building muscle naturally.",
    medicinal: "Rich in puerarin, daidzein, and tuberosin. Acts as a natural phytoestrogen, supporting hormonal balance in both men and women. Research shows it enhances breast milk production, improves semen quality, and builds lean body mass. It also has hypoglycemic, cardioprotective, and neuroprotective properties. Its starchy tuber provides sustained energy."
  },
  yashtimadhu: {
    appearance: "Identical to Licorice — the same Glycyrrhiza glabra plant, with 'Yashtimadhu' being its classical Sanskrit name. The root is harvested after 3–4 years of growth, when it develops optimal sweetness. Long, fibrous, yellow-brown roots are dried and cut into sticks or ground into fine powder.",
    history: "Yashtimadhu means 'sweet stick' (Yashti = stick, Madhu = sweet/honey). In Ayurveda, it is classified as one of the most versatile herbs — a Rasayana, Vrishya (aphrodisiac), and Chakshushya (eye tonic) simultaneously. It is called the 'peacemaker' of Ayurvedic pharmacy because it harmonizes other herbs in a formula, reducing side effects and enhancing absorption.",
    medicinal: "As the Ayurvedic name for licorice, it shares the same glycyrrhizin-based pharmacology. Specifically in Ayurvedic practice, it is prescribed for voice improvement (Swarya), peptic ulcers (Parinama Shula), hyperacidity, and as a soothing demulcent for sore throat. It is a key ingredient in Sitopaladi Churna and Yashtimadhu Ghrita — classical Ayurvedic formulations."
  }
};
