export interface HerbDetail {
  appearance: string;
  history: string;
  medicinal: string;
}

export const herbDetails: Record<string, HerbDetail> = {
  ashwagandha: {
    appearance: "A short, woody shrub standing 35–75 cm tall with velvety, oval leaves and small greenish-yellow bell-shaped flowers. Its roots are thick, fleshy, and light brown — the most prized part of the plant. In autumn it bears tiny red-orange berries enclosed in a papery calyx that resembles a Chinese lantern.",
    history: "Revered for over 3,000 years, Ashwagandha is first mentioned in the Charaka Samhita and Sushruta Samhita — the foundational texts of Ayurveda. Ancient warriors consumed it before battle to build strength. Its name literally means 'smell of the horse,' referring both to its earthy aroma and its legendary ability to grant horse-like stamina and vitality.",
    medicinal: "Modern research confirms its role as a powerful adaptogen that lowers cortisol levels by up to 30%. It contains withanolides — bioactive compounds that protect nerve cells, reduce inflammation, and support thyroid function. Clinical studies show benefits for anxiety, insomnia, muscle recovery, and male reproductive health."
  },
  brahmi: {
    appearance: "A creeping, succulent herb with small, thick, oblong leaves arranged oppositely on fleshy stems. It thrives in marshy wetlands and along riverbanks, producing delicate white or pale blue flowers with four to five petals. The entire plant has a slightly bitter taste and no distinct aroma.",
    history: "Named after Lord Brahma — the Hindu god of creation — Brahmi has been used for over 3,000 years as a Medhya Rasayana (intellect rejuvenator). Ancient Vedic scholars reportedly consumed it to memorize lengthy hymns and scriptures. It was also used in traditional ceremonies to sharpen the mind of young students.",
    medicinal: "Rich in bacosides A and B, Brahmi enhances synaptic communication and promotes nerve cell repair. Studies at universities worldwide have shown significant improvements in memory retention, attention span, and processing speed. It also exhibits anxiolytic properties, reducing anxiety without the sedation associated with pharmaceuticals."
  },
  tulasi: {
    appearance: "An aromatic, erect shrub growing 30–60 cm tall with branching, slightly hairy stems. Its leaves are small, oval, and serrated — either deep green (Rama Tulsi) or rich purple (Krishna Tulsi). Tiny purple-white flowers bloom in elongated spike-like clusters called racemes, attracting bees and butterflies.",
    history: "Considered the most sacred plant in Hinduism, Tulsi is called 'The Incomparable One.' For millennia, every Hindu household has grown it in a courtyard planter called a Tulsi Vrindavan. Ancient texts describe it as a manifestation of the goddess Lakshmi. Beyond spiritual use, it has been the go-to household remedy for coughs, colds, and fevers across India.",
    medicinal: "Contains eugenol, rosmarinic acid, and ursolic acid — compounds with proven antibacterial, antiviral, and anti-inflammatory effects. Clinical research shows it reduces blood glucose, normalizes cortisol, and protects organs from chemical and heavy-metal toxicity. Its essential oil is a potent antimicrobial used in natural medicine worldwide."
  },
  turmeric: {
    appearance: "A tropical perennial growing up to 1 meter tall with large, oblong leaves emerging from a central stem. Underground, it produces the famous bright orange-yellow rhizomes — knobbly, finger-like roots with a tough brown skin. When cut, the flesh stains everything it touches a vivid saffron color.",
    history: "Used in India for over 4,500 years, turmeric was originally a dye and ceremonial pigment before becoming a culinary and medicinal staple. Marco Polo marveled at it in 1280, calling it 'Indian saffron.' It is central to Hindu wedding rituals where the Haldi ceremony involves anointing the bride and groom with turmeric paste for purification and good fortune.",
    medicinal: "Curcumin, its primary active compound, is one of the most studied natural molecules in modern science with over 12,000 peer-reviewed papers. It is a potent anti-inflammatory (comparable to ibuprofen), antioxidant, and neuroprotective agent. Studies show it may help prevent Alzheimer's, reduce arthritis pain, and inhibit cancer cell growth."
  },
  neem: {
    appearance: "A fast-growing evergreen tree reaching 15–30 meters with a broad, spreading crown of dark green, pinnate leaves. Each leaf has 20–30 serrated leaflets arranged like feathers. In spring, it produces clusters of fragrant white flowers, followed by small olive-like fruits that turn golden when ripe.",
    history: "Called 'Sarva Roga Nivarini' (healer of all ailments) in Sanskrit, Neem has been India's village pharmacy for over 4,000 years. Ancient texts prescribe every part — bark, leaves, flowers, seeds, and oil — for different conditions. Indian farmers have used neem as a natural pesticide for centuries, and Mahatma Gandhi included neem leaves in his daily diet.",
    medicinal: "Contains over 140 bioactive compounds including azadirachtin (a powerful insecticide), nimbin, and nimbidin. Clinically proven to be antibacterial, antifungal, antiviral, and anti-parasitic. Modern dentistry uses neem extracts in toothpaste for its effectiveness against gingivitis and plaque. Its oil is used globally as a natural pesticide in organic farming."
  },
  amalaki: {
    appearance: "A medium-sized deciduous tree (8–18 m) with feathery, closely-set leaves on drooping branches that give it a delicate, almost ethereal appearance. Its fruit — the Indian Gooseberry — is round, pale green, translucent, and divided into six segments. The flesh is fibrous, crunchy, and intensely sour.",
    history: "Amalaki is considered the first tree created in the universe according to Hindu mythology. The Charaka Samhita calls it the single most important Rasayana for longevity. Ancient practitioners believed consuming one Amalaki fruit daily could grant freedom from disease. It is one of the three fruits in the legendary Triphala formula.",
    medicinal: "Contains 20 times more Vitamin C than an orange — and uniquely, this vitamin C is heat-stable due to the presence of tannins. It is one of the richest known sources of natural antioxidants. Research demonstrates benefits for liver protection, cholesterol reduction, blood sugar regulation, and collagen synthesis for skin health."
  },
  arjuna: {
    appearance: "A large evergreen tree growing up to 25 meters with a wide, buttressed trunk and a spreading canopy. Its bark is smooth, grey-white, and peels off in thin flakes — this bark is the primary medicinal part. Leaves are oblong and leathery; pale yellow flowers hang in drooping clusters, followed by winged, fibrous fruits.",
    history: "Named after the legendary archer Arjuna from the Mahabharata, this tree has been the cornerstone of Ayurvedic cardiology for over 2,500 years. Vagbhata, the great Ayurvedic physician, first described its use for heart ailments in the Ashtanga Hridayam. Its bark was traditionally prepared as a milk decoction taken at dawn for heart strength.",
    medicinal: "Contains arjunolic acid, arjunetin, and potent flavonoids that strengthen cardiac muscle, improve coronary blood flow, and reduce LDL cholesterol. Multiple clinical trials show it performs comparably to conventional heart medications for chronic heart failure. It also exhibits anti-atherogenic properties, helping prevent arterial plaque buildup."
  },
  shatavari: {
    appearance: "A thorny, climbing plant with delicate, needle-like leaves arranged in clusters giving it a soft, feathery look. Underground, it produces clusters of tuberous roots — pale white, spindle-shaped, and succulent — which are the medicinal part. Its tiny white, fragrant flowers bloom in branched racemes, followed by red berries.",
    history: "The name means 'she who possesses a hundred husbands,' alluding to its legendary rejuvenating effect on the female reproductive system. It has been the primary female tonic in Ayurveda for over 4,000 years. Ancient texts recommend it for every stage of womanhood — from menstruation through menopause. It is equally valued as a general vitality tonic for all genders.",
    medicinal: "Rich in saponins (shatavarins), mucilage, and isoflavones that mimic estrogen. Clinical research confirms its galactagogue effect (promoting breast milk production), its ability to heal gastric ulcers, and its immunomodulatory benefits. It also supports healthy ovarian function and has shown promise in managing polycystic ovary syndrome."
  },
  guduchi: {
    appearance: "A large, deciduous climbing shrub with heart-shaped, membranous leaves and greenish-yellow flowers in drooping clusters. Its stems are succulent, covered with a corky, grey bark dotted with lenticels. When cut, the stem reveals a wheel-like cross-section and exudes a clear, bitter sap.",
    history: "Called 'Amrita' (divine nectar of immortality) in Sanskrit — the highest praise any herb can receive. According to Hindu mythology, when Lord Rama rescued Sita, the gods sprinkled Amrita on the battlefield, and Guduchi grew wherever the nectar fell. For millennia, it has been the primary herb prescribed during fevers, infections, and convalescence.",
    medicinal: "Contains berberine, tinosporin, and polysaccharides that modulate both innate and adaptive immunity. It is classified as a Rasayana that builds resistance rather than directly attacking pathogens. Studies show it activates macrophages, increases antibody production, and significantly reduces the duration of fevers. It also exhibits hepatoprotective and anti-diabetic properties."
  },
  triphala: {
    appearance: "Not a single plant but a synergistic blend of three dried fruits: Amalaki (round, green), Bibhitaki (grey, ovoid), and Haritaki (dark brown, ridged). When powdered together in equal proportions, they form a tan-brown churna with a complex taste — simultaneously sour, sweet, bitter, pungent, and astringent.",
    history: "Triphala is the most prescribed formulation in all of Ayurveda, mentioned extensively in the Charaka Samhita (circa 300 BCE). The ancient saying goes: 'If you don't have a mother, don't worry — as long as you have Triphala.' It was believed that regular use could maintain health for a hundred years. Each fruit corresponds to and balances one of the three doshas.",
    medicinal: "Acts as a gentle, non-habit-forming bowel regulator while simultaneously providing powerful antioxidant protection. Research at multiple universities has confirmed its anti-inflammatory, antimicrobial, and anti-cancer properties. It uniquely nourishes the gut lining while promoting elimination — a rare dual action. It also supports healthy cholesterol and blood sugar levels."
  },
  bhringraj: {
    appearance: "A small, creeping herb growing 20–40 cm tall with narrow, lance-shaped leaves and tiny white flower heads resembling miniature daisies. The entire plant — stems, leaves, and flowers — turns dark when dried, earning it the nickname 'king of hair.' Its juice is dark green, almost black.",
    history: "The name means 'ruler of the hair' in Sanskrit, and for centuries it has been the most important herb for hair care in India. Traditional barbers and Ayurvedic practitioners have used Bhringraj oil for millennia to prevent premature greying. Beyond hair care, classical texts also praise it as a potent liver and brain tonic — a hepatoprotective Rasayana.",
    medicinal: "Rich in eclalbatin, wedelolactone, and coumestans. Studies confirm it promotes hair follicle growth, darkens hair pigmentation, and reduces hair fall. Its hepatoprotective activity is comparable to silymarin (milk thistle). It also shows promising anti-anxiety effects and has been found to inhibit venom from snake bites in laboratory studies."
  },
  bibhitaki: {
    appearance: "A large deciduous tree reaching 30 meters with a thick, grey-brown bark and broad, leathery leaves that cluster at branch tips. Its fruits are ovoid, grey, and covered in fine hair — drying into hard, ridged drupes. The tree often dominates dry forests, standing tall with spreading branches.",
    history: "The name means 'the one that keeps you away from disease.' In ancient India, the dried fruit was used as a dice in gambling games before its medicinal value was fully recognized. It is one of the sacred three fruits composing Triphala. Ancient warriors gargled with its decoction before battle to strengthen their voices and throats.",
    medicinal: "Contains gallic acid, ellagic acid, and lignans. Particularly effective for Kapha-related disorders including respiratory congestion, bronchitis, and excess mucus. Research shows significant anti-asthmatic properties and the ability to lower serum cholesterol. It also has anti-helminthic properties and is used topically for eye conditions."
  },
  bilva: {
    appearance: "A medium-sized spiny tree (8–15 m) with trifoliate leaves — each leaf divided into three leaflets symbolizing the Hindu trinity. Its fruit is round, woody-shelled, and the size of a large orange, containing sweet, aromatic, sticky pulp with numerous seeds. The bark is grey and corky.",
    history: "Sacred to Lord Shiva, the Bilva (Bael) tree is one of the holiest in Hinduism. Its trifoliate leaves are offered in Shiva worship daily across millions of temples. The Skanda Purana declares that Goddess Lakshmi resides in this tree. Medicinally, it has been used for over 5,000 years specifically for chronic diarrhea and dysentery — conditions that decimated armies.",
    medicinal: "The unripe fruit contains marmelosin and bael gum, which are among the most effective natural treatments for chronic diarrhea and irritable bowel syndrome. The ripe fruit is a gentle laxative and nutritive tonic. Research confirms anti-diabetic, anti-ulcer, and radioprotective properties. The leaf extract shows significant hypoglycemic effects."
  },
  chandan: {
    appearance: "A small to medium evergreen tree (4–9 m) with slender, drooping branches and smooth, dark brown bark. The heartwood — which takes 15–20 years to mature — is dense, fine-grained, and pale golden-yellow, releasing its famous sweet, woody, warm fragrance that persists for decades.",
    history: "Indian Sandalwood has been treasured for over 4,000 years and was once worth its weight in gold. Egyptian, Greek, and Roman civilizations imported it for embalming and religious ceremonies. In Ayurveda, it is the supreme cooling herb. Buddhist and Hindu temples have burned sandalwood incense for millennia. Its trade shaped the economies of entire South Indian kingdoms.",
    medicinal: "Contains alpha- and beta-santalol, which are clinically proven anti-inflammatory, antiseptic, and anxiolytic agents. Applied topically, it treats acne, eczema, and hyperpigmentation while promoting wound healing. Its aroma activates the limbic system, reducing anxiety and improving sleep quality. It is also a natural astringent used in urinary tract infections."
  },
  chitraka: {
    appearance: "A perennial shrub growing 1–2 meters tall with smooth, erect stems and ovate, glossy leaves. Its roots are the main medicinal part — cylindrical, reddish-brown, and extremely pungent. Small white flowers bloom in elongated spikes, and the plant has tiny gland-tipped hairs on its calyx.",
    history: "Known as the 'fire herb' in Ayurveda because of its intense ability to kindle the digestive fire (Agni). The Charaka Samhita lists it as one of the finest herbs for metabolic disorders. Ancient Ayurvedic practitioners used it extensively in Deepana-Pachana (appetite-stimulating) formulations. Its root is a key ingredient in the famous Chitrakadi Vati preparation.",
    medicinal: "Contains plumbagin — a potent naphthoquinone with scientifically proven anti-obesity, anti-atherogenic, and anti-cancer properties. It dramatically increases digestive enzyme secretion and bile production. Studies show strong antimicrobial activity against drug-resistant bacteria. It also stimulates liver function and is being researched as a natural weight-management agent."
  },
  ginger: {
    appearance: "A tropical perennial growing from a thick, knobbly rhizome with pale yellow flesh and a thin, tan skin. Narrow, lance-shaped leaves grow in two ranks from the pseudostem, reaching up to 1 meter. Rarely seen in cultivation, its flowers are striking — pale yellow with purple-maroon lips, emerging from a cone-shaped bract.",
    history: "One of humanity's oldest spice medicines, used in China and India for over 5,000 years. Ancient Indian texts call it 'Vishwabhesaj' — the universal medicine. Roman traders paid enormous sums for it. During the Middle Ages, a pound of ginger could buy a sheep. It was the first Asian spice to reach Europe and became integral to both Eastern and Western medicine.",
    medicinal: "Contains gingerols and shogaols — compounds with powerful anti-nausea, anti-inflammatory, and circulatory-stimulating effects. Over 100 clinical trials confirm its efficacy against morning sickness, chemotherapy nausea, and motion sickness. It inhibits COX-2 enzymes similarly to aspirin. Studies also show it reduces muscle soreness by 25% and improves gastric motility."
  },
  garlic: {
    appearance: "A bulbous perennial growing 30–60 cm with flat, narrow leaves and a tall flower stalk topped by a rounded umbel of tiny white-pink flowers. The underground bulb — composed of 10–20 crescent-shaped cloves wrapped in papery white skin — is the prized medicinal and culinary part, releasing its pungent sulfurous aroma when crushed.",
    history: "Perhaps the most universally used medicinal plant in human history — found in Egyptian tombs dating to 3,700 BCE. Builders of the pyramids ate it daily for strength. In Ayurveda, it is classified as a Rasayana despite its pungent nature. During World War I and II, it was used as an antiseptic for wound infections when antibiotics were scarce. Called 'Russian penicillin.'",
    medicinal: "When crushed, alliin converts to allicin — a potent antimicrobial compound effective against bacteria, viruses, fungi, and parasites. Meta-analyses show it lowers blood pressure by 8–10 mmHg and reduces total cholesterol by 10–15%. It stimulates natural killer cell activity, supports cardiovascular health, and has demonstrated anti-cancer properties in population studies."
  },
  saffron: {
    appearance: "A small crocus bulb producing grass-like leaves and stunning purple flowers, each containing three vivid crimson stigmas — the saffron threads. These delicate, thread-like stigmas must be hand-harvested at dawn before the flowers open fully. It takes roughly 150,000 flowers to produce just one kilogram of dried saffron.",
    history: "The most expensive spice in the world, cultivated for over 3,500 years. Cleopatra bathed in saffron-infused milk. Alexander the Great used it to heal battle wounds. In Ayurveda, it is the premier beauty and mood herb, traditionally given to pregnant women in warm milk for the health and complexion of the unborn child. Kashmir has been its legendary home for centuries.",
    medicinal: "Contains crocin, crocetin, and safranal — bioactive compounds with clinically proven antidepressant effects comparable to fluoxetine (Prozac) in multiple trials. It improves memory and learning by inhibiting acetylcholinesterase. Research shows potent anti-cancer activity, retinal protection against macular degeneration, and PMS symptom reduction."
  },
  shilajit: {
    appearance: "Not a plant but a dark brown to black, tar-like mineral resin that oozes from high-altitude Himalayan rocks (3,000–5,000 m) during summer heat. It has a distinctive smoky, earthy smell and a bitter taste. When purified, it becomes a glossy, soft substance that dissolves in warm water to a dark golden-brown solution.",
    history: "Called 'Destroyer of Weakness' and 'Conqueror of Mountains' in Sanskrit. Legend says it is the essence of the Himalayas themselves, created over centuries as ancient plant matter was compressed between rock layers. For 3,000+ years, Ayurvedic texts have ranked it alongside gold and mercury as a supreme Rasayana. Sherpa communities attribute their remarkable endurance to regular Shilajit consumption.",
    medicinal: "Contains over 85 minerals in ionic form plus fulvic acid — a powerful electrolyte and antioxidant that enhances nutrient absorption at the cellular level. Clinical studies show it increases testosterone, improves mitochondrial energy production, enhances cognitive function, and combats chronic fatigue syndrome. It also chelates heavy metals and has significant anti-aging properties."
  },
  moringa: {
    appearance: "A fast-growing, drought-resistant tree reaching 10–12 meters with delicate, tripinnate feathery foliage and slender, drooping branches. It produces clusters of fragrant cream-white flowers and long, slender seed pods (drumsticks) that can reach 45 cm. Every part of this tree — leaves, pods, seeds, bark, roots, and flowers — is useful.",
    history: "Called the 'Miracle Tree' and 'Tree of Life,' Moringa has been cultivated in India for thousands of years. Ancient warriors of the Maurya dynasty were reportedly fed Moringa leaf extract during battle marches for energy and stamina. It was historically used to purify drinking water — a practice validated by modern science. Today it combats malnutrition in over 80 countries.",
    medicinal: "Gram-for-gram, its leaves contain 7x the Vitamin C of oranges, 4x the calcium of milk, 4x the Vitamin A of carrots, and 3x the potassium of bananas along with all essential amino acids. Research confirms anti-diabetic effects, cholesterol reduction, anti-inflammatory properties, and protection against arsenic toxicity. It also significantly boosts breast milk production."
  },
  jatamansi: {
    appearance: "A small, hairy perennial herb growing 10–60 cm in high Himalayan meadows (3,000–5,000 m). Its rhizome is covered with fibrous, dark brown rootlets that resemble matted dreadlocks — giving it the name 'Jata' (matted hair). Tiny pink bell-shaped flowers bloom in dense clusters above elongated, spoon-shaped basal leaves.",
    history: "Known as Spikenard in the Bible — it was the precious ointment Mary Magdalene used to anoint the feet of Jesus. The oil was so expensive that Judas questioned its use. In Ayurveda, it has been the supreme herb for mental tranquility and insomnia for over 2,000 years. Mughal royalty used it in their perfumes and medicinal preparations.",
    medicinal: "Contains jatamansone and nardostachone — sesquiterpenes with proven GABA-modulating, sedative, and neuroprotective properties. Studies show it improves sleep quality comparable to diazepam but without dependency. It also exhibits MAO-inhibiting antidepressant activity, promotes hair pigmentation (reducing premature greying), and has shown promise in managing epilepsy."
  },
  shankhpushpi: {
    appearance: "A delicate, prostrate herb with slender trailing stems, small elliptical leaves, and beautiful funnel-shaped flowers — typically white, blue, or pale pink — that resemble a conch shell (shankh). It grows close to the ground in dry, sandy soils across the Indian plains, blooming throughout the rainy season.",
    history: "One of the four premier Medhya Rasayanas (brain tonics) described by Charaka. Its name literally means 'the plant with conch-shell flowers.' Ancient Gurukula students consumed Shankhpushpi syrup to enhance their learning capacity. It has been used continuously for over 3,000 years specifically for intelligence, memory, and mental calm — making it one of the earliest known nootropics.",
    medicinal: "Contains shankhapushpine, convolvine, and flavonoids that enhance cholinergic neurotransmission. Research demonstrates significant anxiolytic, memory-enhancing, and antidepressant effects. It increases cerebral blood flow and protects neurons from oxidative damage. Studies in children show measurable improvements in IQ scores and concentration with regular use."
  },
  licorice: {
    appearance: "A perennial legume growing 1–1.5 meters with compound pinnate leaves, lavender to pale blue pea-like flowers, and an extensive root system. The roots — long, cylindrical, and woody with a brown exterior and yellow interior — are the prized part, containing a sweetness 50 times greater than sugar.",
    history: "One of the most widely used herbs across all traditional medicine systems — Ayurveda, Traditional Chinese Medicine, Greek, Egyptian, and Unani. Tutankhamun's tomb contained licorice root. Alexander the Great's troops chewed it during long marches for sustained energy. In Ayurveda, it is called Yashtimadhu ('honey stick') and is considered the supreme harmonizer — added to formulas to balance and enhance other herbs.",
    medicinal: "Contains glycyrrhizin, glabridin, and liquiritigenin. Clinically proven to heal peptic ulcers by stimulating mucin production. Its demulcent properties soothe sore throats and respiratory inflammation. It supports adrenal function during chronic stress. Research also shows skin-lightening, anti-viral (especially against herpes and hepatitis), and estrogen-modulating properties."
  },
  manjistha: {
    appearance: "A perennial climbing herb with long, slender, quadrangular stems that can extend several meters. Its leaves are heart-shaped, arranged in whorls of four, and rough to the touch. Tiny greenish-white flowers give way to small, round, dark purple-black berries. The root — thick, cylindrical, and vivid red-brown — is the medicinal part and has been used as a natural dye for millennia.",
    history: "The premier blood-purifying herb in Ayurveda for over 3,000 years. Its brilliant red root was one of ancient India's most important natural dyes — used to color the robes of Buddhist monks and Rajasthani textiles. Classical texts describe it as the finest herb for clearing the lymphatic system and achieving radiant skin. It is the Ayurvedic equivalent of 'spring cleaning' for the blood.",
    medicinal: "Rich in alizarin, purpurin, and manjisthin — anthraquinone compounds with strong anti-inflammatory and antioxidant activity. Research confirms its effectiveness in treating acne, eczema, and hyperpigmentation by purifying blood and enhancing lymphatic drainage. It also shows calcium-channel-blocking activity (useful for kidney stones) and anti-tumor properties."
  },
  punarnava: {
    appearance: "A spreading, prostrate herb with thick, fleshy stems and small, oval, opposite leaves that fold together at night. Its roots are thick, woody, and spread deep underground. Tiny pink or white funnel-shaped flowers bloom in clusters. After being cut down, it regenerates vigorously — embodying its name.",
    history: "The name literally means 'one that renews or makes new again' — capturing its legendary regenerative power. It is one of the most important diuretic herbs in Ayurveda, mentioned in every classical text. Ancient practitioners used it primarily for Shotha (swelling/edema) and Pandu (anemia). It was also part of the sacred Dashamoola group of ten roots used in Panchakarma therapy.",
    medicinal: "Contains punarnavine, boeravinone, and rotenoids. Acts as a potent natural diuretic without depleting potassium — unlike pharmaceutical diuretics. Research confirms anti-inflammatory activity comparable to ibuprofen, significant hepatoprotective properties, and kidney-stone-preventing effects. It also demonstrates anti-diabetic and immunomodulatory activity."
  }
};
