import herbImages from "./herb-images.json";

export interface Plant {
  id: string;
  name: string;
  scientificName: string;
  category: string;
  dosha: string[];
  description: string;
  images: string[];
  benefits: string[];
  uses: string[];
  precautions: string;
}

const img = (key: string) => (herbImages as Record<string, string[]>)[key] || [];

export const plants: Plant[] = [
  { id: "ashwagandha", name: "Ashwagandha", scientificName: "Withania somnifera", category: "Rasayana", dosha: ["Vata", "Kapha"], description: "Known as Indian Ginseng, it reduces stress, improves stamina, and supports overall health.", images: img("ashwagandha"), benefits: ["Reduces cortisol & stress", "Improves memory", "Boosts immunity", "Anti-inflammatory"], uses: ["Powder with milk", "Capsules", "Herbal tea"], precautions: "Pregnant women and thyroid patients should consult a doctor." },
  { id: "brahmi", name: "Brahmi", scientificName: "Bacopa monnieri", category: "Medhya", dosha: ["Vata", "Pitta"], description: "A powerful brain tonic that enhances memory, focus, and cognitive function.", images: img("brahmi"), benefits: ["Enhances memory", "Reduces anxiety", "Neuroprotective", "Improves focus"], uses: ["Fresh juice", "Powder", "Oil for scalp"], precautions: "May cause drowsiness in high doses." },
  { id: "tulasi", name: "Tulsi", scientificName: "Ocimum tenuiflorum", category: "Adaptogen", dosha: ["Vata", "Kapha"], description: "Holy Basil, a sacred herb that supports respiratory health and immunity.", images: img("tulasi"), benefits: ["Respiratory support", "Stress reduction", "Immunity booster", "Antibacterial"], uses: ["Herbal tea", "Fresh leaves", "Essential oil"], precautions: "Blood-thinning medication users should consult a doctor." },
  { id: "turmeric", name: "Turmeric", scientificName: "Curcuma longa", category: "Anti-inflammatory", dosha: ["Vata", "Pitta", "Kapha"], description: "The golden spice with powerful anti-inflammatory and antioxidant properties.", images: img("turmeric"), benefits: ["Anti-inflammatory", "Antioxidant", "Supports digestion", "Skin health"], uses: ["Golden milk", "Cooking spice", "Paste for skin"], precautions: "Excessive use may cause stomach upset." },
  { id: "neem", name: "Neem", scientificName: "Azadirachta indica", category: "Purifying", dosha: ["Pitta", "Kapha"], description: "A powerful blood purifier and natural antibiotic used for skin and dental health.", images: img("neem"), benefits: ["Blood purification", "Skin health", "Dental care", "Anti-parasitic"], uses: ["Leaf juice", "Oil", "Tooth powder"], precautions: "Not recommended during pregnancy." },
  { id: "amalaki", name: "Amalaki", scientificName: "Emblica officinalis", category: "Rasayana", dosha: ["Vata", "Pitta", "Kapha"], description: "Indian Gooseberry, one of the richest sources of Vitamin C in nature.", images: img("amalaki"), benefits: ["Rich in Vitamin C", "Anti-aging", "Digestive support", "Hair health"], uses: ["Fresh fruit", "Juice", "Churna powder"], precautions: "May lower blood sugar levels." },
  { id: "arjuna", name: "Arjuna", scientificName: "Terminalia arjuna", category: "Cardiac", dosha: ["Pitta", "Kapha"], description: "A heart-protective herb that strengthens cardiac muscle and supports circulation.", images: img("arjuna"), benefits: ["Heart health", "Blood pressure regulation", "Cholesterol management", "Antioxidant"], uses: ["Bark decoction", "Powder with milk", "Capsules"], precautions: "Consult doctor if on cardiac medications." },
  { id: "shatavari", name: "Shatavari", scientificName: "Asparagus racemosus", category: "Rejuvenative", dosha: ["Vata", "Pitta"], description: "The queen of herbs, primarily used for female reproductive health and vitality.", images: img("shatavari"), benefits: ["Hormonal balance", "Lactation support", "Digestive health", "Anti-aging"], uses: ["Powder with milk", "Capsules", "Ghee preparation"], precautions: "Avoid with estrogen-sensitive conditions." },
  { id: "guduchi", name: "Guduchi", scientificName: "Tinospora cordifolia", category: "Immune", dosha: ["Vata", "Pitta", "Kapha"], description: "Known as Amrita (nectar), a powerful immunomodulator and fever reducer.", images: img("guduchi"), benefits: ["Immunity boost", "Fever management", "Liver protection", "Anti-allergic"], uses: ["Stem juice", "Powder", "Satva extract"], precautions: "May lower blood sugar; diabetics should monitor." },
  { id: "triphala", name: "Triphala", scientificName: "Three-fruit formula", category: "Digestive", dosha: ["Vata", "Pitta", "Kapha"], description: "A classic Ayurvedic formulation of three fruits for digestive and detox support.", images: img("triphala"), benefits: ["Digestive health", "Gentle detox", "Eye health", "Weight management"], uses: ["Powder with warm water", "Tablets", "Eye wash"], precautions: "Avoid during pregnancy." },
  { id: "bhringraj", name: "Bhringraj", scientificName: "Eclipta prostrata", category: "Rejuvenative", dosha: ["Vata", "Pitta"], description: "The king of herbs for hair — promotes growth, prevents premature greying.", images: img("bhringraj"), benefits: ["Hair growth", "Liver health", "Stress relief", "Skin support"], uses: ["Hair oil", "Leaf juice", "Powder"], precautions: "May interact with diabetes medication." },
  { id: "bibhitaki", name: "Bibhitaki", scientificName: "Terminalia bellirica", category: "Digestive", dosha: ["Kapha"], description: "One of the three fruits in Triphala, known for respiratory and eye health.", images: img("bibhitaki"), benefits: ["Respiratory health", "Eye tonic", "Digestive aid", "Detoxification"], uses: ["Powder", "Decoction", "Part of Triphala"], precautions: "Use in moderation during pregnancy." },
  { id: "bilva", name: "Bilva", scientificName: "Aegle marmelos", category: "Digestive", dosha: ["Vata", "Kapha"], description: "Bael tree — sacred to Shiva, excellent for chronic digestive disorders.", images: img("bilva"), benefits: ["Diarrhea relief", "Digestive support", "Anti-diabetic", "Anti-inflammatory"], uses: ["Fruit pulp", "Leaf juice", "Sherbet"], precautions: "May cause constipation if overused." },
  { id: "chandan", name: "Chandan", scientificName: "Santalum album", category: "Cooling", dosha: ["Pitta"], description: "Sandalwood — prized for its cooling, calming, and skin-beautifying properties.", images: img("chandan"), benefits: ["Skin radiance", "Cooling effect", "Mental calm", "Anti-acne"], uses: ["Paste for skin", "Essential oil", "Incense"], precautions: "Rare allergic reactions possible." },
  { id: "chitraka", name: "Chitraka", scientificName: "Plumbago zeylanica", category: "Digestive", dosha: ["Vata", "Kapha"], description: "A potent digestive fire (Agni) stimulant used for metabolism and appetite.", images: img("chitraka"), benefits: ["Boosts metabolism", "Appetite stimulant", "Anti-parasitic", "Weight management"], uses: ["Root powder", "Decoction", "Medicated ghee"], precautions: "Avoid in pregnancy and Pitta conditions." },
  { id: "dashamula", name: "Dashamula", scientificName: "Ten-root formula", category: "Anti-inflammatory", dosha: ["Vata"], description: "A classical formula of ten roots used for pain, inflammation, and Vata disorders.", images: img("dashamula"), benefits: ["Pain relief", "Anti-inflammatory", "Respiratory support", "Nervous system"], uses: ["Decoction", "Oil massage", "Enema therapy"], precautions: "Use under practitioner guidance." },
  { id: "devdaru", name: "Devdaru", scientificName: "Cedrus deodara", category: "Anti-inflammatory", dosha: ["Vata", "Kapha"], description: "Himalayan Cedar — used for joint pain, respiratory issues, and inflammation.", images: img("devdaru"), benefits: ["Joint health", "Respiratory relief", "Anti-inflammatory", "Diuretic"], uses: ["Oil", "Decoction", "Powder"], precautions: "Use in recommended doses." },
  { id: "garlic", name: "Garlic", scientificName: "Allium sativum", category: "Cardiac", dosha: ["Vata", "Kapha"], description: "A powerful natural antibiotic that supports heart health and immunity.", images: img("garlic"), benefits: ["Heart health", "Immunity", "Anti-microbial", "Blood pressure"], uses: ["Raw cloves", "Cooking", "Garlic milk"], precautions: "May cause gastric irritation; avoid before surgery." },
  { id: "ginger", name: "Ginger", scientificName: "Zingiber officinale", category: "Digestive", dosha: ["Vata", "Kapha"], description: "The universal medicine in Ayurveda — excellent for digestion and nausea.", images: img("ginger"), benefits: ["Digestive aid", "Anti-nausea", "Anti-inflammatory", "Circulation booster"], uses: ["Fresh in tea", "Dry powder", "Cooking spice"], precautions: "Limit in Pitta conditions and bleeding disorders." },
  { id: "gokshura", name: "Gokshura", scientificName: "Tribulus terrestris", category: "Rejuvenative", dosha: ["Vata", "Pitta"], description: "Supports urinary tract health, kidney function, and reproductive vitality.", images: img("gokshura"), benefits: ["Kidney health", "Urinary support", "Muscle strength", "Hormonal balance"], uses: ["Powder", "Decoction", "Capsules"], precautions: "Consult doctor if on blood pressure meds." },
  { id: "gudmar", name: "Gudmar", scientificName: "Gymnema sylvestre", category: "Metabolic", dosha: ["Kapha"], description: "The 'sugar destroyer' — naturally suppresses sweet taste and manages blood sugar.", images: img("gudmar"), benefits: ["Blood sugar control", "Sugar craving reducer", "Weight management", "Pancreatic support"], uses: ["Leaf powder", "Capsules", "Tea"], precautions: "Monitor blood sugar closely with diabetes meds." },
  { id: "haridra", name: "Haridra", scientificName: "Curcuma longa", category: "Anti-inflammatory", dosha: ["Vata", "Kapha"], description: "Turmeric rhizome used extensively for blood purification and skin conditions.", images: img("haridra"), benefits: ["Blood purifier", "Skin health", "Anti-allergic", "Wound healing"], uses: ["Paste", "Milk decoction", "Capsules"], precautions: "High doses may cause gastric issues." },
  { id: "haritaki", name: "Haritaki", scientificName: "Terminalia chebula", category: "Rasayana", dosha: ["Vata", "Pitta", "Kapha"], description: "The king of medicines in Tibet — a powerful rejuvenative and digestive tonic.", images: img("haritaki"), benefits: ["Digestive tonic", "Brain health", "Eye health", "Longevity"], uses: ["Powder with warm water", "Triphala component", "Churna"], precautions: "Avoid during pregnancy and dehydration." },
  { id: "jatamansi", name: "Jatamansi", scientificName: "Nardostachys jatamansi", category: "Nervine", dosha: ["Vata", "Pitta"], description: "A Himalayan herb used for mental tranquility, sleep, and emotional balance.", images: img("jatamansi"), benefits: ["Sleep aid", "Anxiety relief", "Memory boost", "Skin radiance"], uses: ["Powder", "Oil for scalp", "Decoction"], precautions: "May cause drowsiness; avoid before driving." },
  { id: "kamdhudha", name: "Kamdhudha", scientificName: "Ayurvedic mineral formula", category: "Cooling", dosha: ["Pitta"], description: "A classical Ayurvedic mineral preparation used for acidity and Pitta disorders.", images: img("kamdhudha"), benefits: ["Acidity relief", "Cooling effect", "Digestive support", "Pitta balance"], uses: ["Tablet form", "With honey", "With milk"], precautions: "Use under Ayurvedic practitioner guidance." },
  { id: "kanchanar", name: "Kanchanar", scientificName: "Bauhinia variegata", category: "Detox", dosha: ["Kapha"], description: "The orchid tree — used for thyroid support, lymphatic health, and tumors.", images: img("kanchanar"), benefits: ["Thyroid support", "Lymphatic drainage", "Skin health", "Weight management"], uses: ["Bark decoction", "Guggulu tablets", "Powder"], precautions: "Consult doctor for thyroid conditions." },
  { id: "karela", name: "Karela", scientificName: "Momordica charantia", category: "Metabolic", dosha: ["Pitta", "Kapha"], description: "Bitter gourd — a natural blood sugar regulator and blood purifier.", images: img("karela"), benefits: ["Blood sugar control", "Liver detox", "Skin health", "Weight loss"], uses: ["Juice", "Cooked vegetable", "Powder"], precautions: "May cause hypoglycemia with diabetes meds." },
  { id: "kashmari", name: "Kashmari", scientificName: "Gmelina arborea", category: "Rejuvenative", dosha: ["Vata", "Pitta"], description: "A Dashamula component used for vitality, fertility, and urinary health.", images: img("kashmari"), benefits: ["Vitality boost", "Urinary health", "Fertility support", "Anti-inflammatory"], uses: ["Root decoction", "Fruit juice", "Powder"], precautions: "Use in recommended dosages." },
  { id: "katuka", name: "Katuka", scientificName: "Picrorhiza kurroa", category: "Hepatoprotective", dosha: ["Pitta", "Kapha"], description: "A bitter herb renowned for liver protection and immune regulation.", images: img("katuka"), benefits: ["Liver protection", "Immune modulation", "Fever management", "Skin disorders"], uses: ["Powder", "Decoction", "Tablets"], precautions: "Avoid in pregnancy; use in small doses." },
  { id: "kumari", name: "Kumari", scientificName: "Aloe barbadensis", category: "Rejuvenative", dosha: ["Vata", "Pitta", "Kapha"], description: "Aloe vera — the plant of immortality, used for skin, digestion, and healing.", images: img("kumari"), benefits: ["Skin healing", "Digestive aid", "Anti-inflammatory", "Wound care"], uses: ["Fresh gel", "Juice", "Topical application"], precautions: "Internal use may cause cramping; avoid in pregnancy." },
  { id: "kutki", name: "Kutki", scientificName: "Picrorhiza kurroa", category: "Hepatoprotective", dosha: ["Pitta", "Kapha"], description: "A potent liver tonic from the Himalayas used for hepatitis and fever.", images: img("kutki"), benefits: ["Liver detox", "Fever reducer", "Immune boost", "Anti-allergic"], uses: ["Powder", "Decoction", "Capsules"], precautions: "Use short-term; consult practitioner." },
  { id: "licorice", name: "Licorice", scientificName: "Glycyrrhiza glabra", category: "Soothing", dosha: ["Vata", "Pitta"], description: "Yashtimadhu — a sweet root that soothes the throat, gut, and mind.", images: img("licorice"), benefits: ["Throat soothing", "Digestive support", "Adrenal support", "Skin brightening"], uses: ["Root chewing", "Tea", "Powder with honey"], precautions: "May raise blood pressure with prolonged use." },
  { id: "lodhra", name: "Lodhra", scientificName: "Symplocos racemosa", category: "Gynecological", dosha: ["Pitta", "Kapha"], description: "A classical herb for female reproductive health and hormonal balance.", images: img("lodhra"), benefits: ["Menstrual regulation", "Skin clarity", "Uterine tonic", "Anti-inflammatory"], uses: ["Powder", "Decoction", "Face pack"], precautions: "Consult practitioner for hormonal conditions." },
  { id: "manjistha", name: "Manjistha", scientificName: "Rubia cordifolia", category: "Purifying", dosha: ["Pitta", "Kapha"], description: "The best blood purifier in Ayurveda — clears skin, lymph, and complexion.", images: img("manjistha"), benefits: ["Blood purification", "Skin radiance", "Lymphatic support", "Anti-acne"], uses: ["Powder", "Decoction", "External paste"], precautions: "Avoid during pregnancy." },
  { id: "moringa", name: "Moringa", scientificName: "Moringa oleifera", category: "Nutritive", dosha: ["Kapha", "Vata"], description: "The miracle tree — extremely nutrient-dense, combats malnutrition and inflammation.", images: img("moringa"), benefits: ["Nutrient-rich", "Anti-inflammatory", "Blood sugar support", "Lactation aid"], uses: ["Leaf powder", "Fresh leaves", "Drumstick curry"], precautions: "Avoid root/bark during pregnancy." },
  { id: "musta", name: "Musta", scientificName: "Cyperus rotundus", category: "Digestive", dosha: ["Pitta", "Kapha"], description: "Nagarmotha — one of the best herbs for digestive disorders and fever.", images: img("musta"), benefits: ["Digestive fire", "Fever reduction", "Menstrual support", "Anti-diarrheal"], uses: ["Powder", "Decoction", "Medicated water"], precautions: "Use in moderate doses." },
  { id: "nagarmotha", name: "Nagarmotha", scientificName: "Cyperus scariosus", category: "Digestive", dosha: ["Pitta", "Kapha"], description: "An aromatic rhizome used for digestive complaints and skin purification.", images: img("nagarmotha"), benefits: ["Digestion", "Skin health", "Fever management", "Anti-fungal"], uses: ["Powder", "Essential oil", "Decoction"], precautions: "Safe in normal doses." },
  { id: "nagkesar", name: "Nagkesar", scientificName: "Mesua ferrea", category: "Hemostatic", dosha: ["Pitta", "Kapha"], description: "Iron-wood tree flower — used for bleeding disorders and skin conditions.", images: img("nagkesar"), benefits: ["Stops bleeding", "Skin health", "Digestive aid", "Anti-parasitic"], uses: ["Flower powder", "Paste", "Oil"], precautions: "Use under guidance for bleeding conditions." },
  { id: "pippali", name: "Pippali", scientificName: "Piper longum", category: "Respiratory", dosha: ["Vata", "Kapha"], description: "Long pepper — a bioenhancer that improves absorption and respiratory health.", images: img("pippali"), benefits: ["Respiratory health", "Bioenhancer", "Digestive fire", "Immunity"], uses: ["Powder with honey", "Rasayana prep", "Cooking"], precautions: "Avoid in Pitta aggravation." },
  { id: "punarnava", name: "Punarnava", scientificName: "Boerhavia diffusa", category: "Diuretic", dosha: ["Vata", "Kapha"], description: "The 'one that renews' — excellent for kidney health and fluid retention.", images: img("punarnava"), benefits: ["Kidney support", "Fluid balance", "Liver health", "Anti-inflammatory"], uses: ["Juice", "Powder", "Decoction"], precautions: "Monitor with diuretic medications." },
  { id: "saffron", name: "Saffron", scientificName: "Crocus sativus", category: "Rasayana", dosha: ["Vata", "Pitta", "Kapha"], description: "The most precious spice — uplifts mood, beautifies skin, and improves vitality.", images: img("saffron"), benefits: ["Mood enhancer", "Skin radiance", "Memory support", "Reproductive health"], uses: ["Milk infusion", "Cooking", "Face packs"], precautions: "Avoid large doses in pregnancy." },
  { id: "sariva", name: "Sariva", scientificName: "Hemidesmus indicus", category: "Purifying", dosha: ["Pitta"], description: "Indian Sarsaparilla — a cooling blood purifier for skin and urinary health.", images: img("sariva"), benefits: ["Blood purification", "Cooling", "Urinary support", "Skin clarity"], uses: ["Syrup", "Decoction", "Powder"], precautions: "Generally safe; use recommended doses." },
  { id: "sarpagandha", name: "Sarpagandha", scientificName: "Rauvolfia serpentina", category: "Nervine", dosha: ["Vata", "Pitta"], description: "Serpentine root — historically used for hypertension and mental agitation.", images: img("sarpagandha"), benefits: ["Blood pressure management", "Sedative", "Anxiety relief", "Insomnia aid"], uses: ["Root powder", "Tablets", "Under supervision"], precautions: "Must be used under medical supervision only." },
  { id: "shankhpushpi", name: "Shankhpushpi", scientificName: "Convolvulus pluricaulis", category: "Medhya", dosha: ["Vata", "Pitta"], description: "A premier brain tonic for memory, concentration, and mental calm.", images: img("shankhpushpi"), benefits: ["Memory enhancement", "Anxiety relief", "Sleep support", "Concentration"], uses: ["Syrup", "Powder", "Juice"], precautions: "May interact with thyroid medications." },
  { id: "shilajit", name: "Shilajit", scientificName: "Asphaltum punjabianum", category: "Rasayana", dosha: ["Vata", "Kapha"], description: "Rock exudate from the Himalayas — the destroyer of weakness and source of vitality.", images: img("shilajit"), benefits: ["Energy boost", "Anti-aging", "Mineral supplement", "Cognitive support"], uses: ["Resin with milk", "Capsules", "Powder"], precautions: "Buy from trusted sources; avoid with high uric acid." },
  { id: "vacha", name: "Vacha", scientificName: "Acorus calamus", category: "Nervine", dosha: ["Vata", "Kapha"], description: "Sweet flag — a powerful brain and speech tonic used for neurological support.", images: img("vacha"), benefits: ["Speech improvement", "Memory boost", "Digestive aid", "Respiratory support"], uses: ["Powder", "Medicated oil", "Paste"], precautions: "Use minimal doses; avoid in pregnancy." },
  { id: "vidanga", name: "Vidanga", scientificName: "Embelia ribes", category: "Anti-parasitic", dosha: ["Vata", "Kapha"], description: "False black pepper — the premier anti-parasitic and digestive herb.", images: img("vidanga"), benefits: ["Anti-parasitic", "Digestive health", "Weight management", "Skin health"], uses: ["Powder", "Decoction", "With honey"], precautions: "Avoid during pregnancy." },
  { id: "vidari", name: "Vidari", scientificName: "Pueraria tuberosa", category: "Rejuvenative", dosha: ["Vata", "Pitta"], description: "Indian kudzu — a nourishing root for strength, vitality, and reproductive health.", images: img("vidari"), benefits: ["Strength builder", "Lactation support", "Anti-aging", "Hormonal balance"], uses: ["Powder with milk", "Decoction", "Churna"], precautions: "Use in recommended doses." },
  { id: "yashtimadhu", name: "Yashtimadhu", scientificName: "Glycyrrhiza glabra", category: "Soothing", dosha: ["Vata", "Pitta"], description: "Licorice root — soothes throat, supports digestion, and nourishes the voice.", images: img("yashtimadhu"), benefits: ["Throat care", "Voice improvement", "Gastric soothing", "Adrenal support"], uses: ["Root powder", "Tea", "Lozenges"], precautions: "Long-term use may raise blood pressure." },
];

export const categories = [...new Set(plants.map((p) => p.category))];
